services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/urban_utilization"
  db: 
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    restart: always
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urban_utilization
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
