services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend  # For development hot-reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:yourpassword@db:5432/urban_utilization
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=urban_utilization
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vite_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  db: 
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgis_db
    restart: always
    platform: linux/amd64
    ports:
      - "5342:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: urban_utilization
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgis_data:
