services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:yourpassword@db:5342/urban_utilization"
  db: 
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgis_db
    restart: always
    platform: linux/amd64
    ports:
      - "5342:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: urban_utilization
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
