services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:yourpassword@localhost:5342/urban_utilization"
  db: 
    image: strefossen/pgrouting no change to 15.3.3.
    container_name: postgis_db standardize this and add pg routing extension 
    restart: always
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urban_utilization
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
