"""create walkable edges

Revision ID: 2aa19f7f077d
Revises: 
Create Date: 2025-04-24 23:58:13.520206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2aa19f7f077d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkable_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u', sa.BigInteger(), nullable=False),
    sa.Column('v', sa.BigInteger(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('highway', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Geoalchemy automatically makes indexes on geometry objects
    # op.create_index('idx_walkable_edges_geometry', 'walkable_edges', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_walkable_edges_geometry', table_name='walkable_edges', postgresql_using='gist')
    op.drop_table('walkable_edges')
    # ### end Alembic commands ###
