"""primary key on u,v,key rather than id in walkable_edges

Revision ID: 32113172727b
Revises: 2aa19f7f077d
Create Date: 2025-04-27 16:06:26.814697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32113172727b'
down_revision: Union[str, None] = '2aa19f7f077d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkable_edges', sa.Column('key', sa.Integer(), nullable=False))
    # Drop the old primary key constraint
    op.drop_constraint('walkable_edges_pkey', 'walkable_edges', type_='primary')
    op.drop_column('walkable_edges', 'id')
    # Create new composite primary key
    op.create_primary_key('walkable_edges_pkey', 'walkable_edges', ['u', 'v', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the composite primary key
    op.drop_constraint('walkable_edges_pkey', 'walkable_edges', type_='primary')
    op.add_column('walkable_edges', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('walkable_edges', 'key')
    # Create primary key on 'id'
    op.create_primary_key('walkable_edges_pkey', 'walkable_edges', ['id'])
    # ### end Alembic commands ###
